### ISSUE TITLE
¿Este cliente ya esta en condiciones de ser usado?

### ISSUE THREAD

**Issue by leamasuero** [mercadopago/dx-php#58]
La documentación beta no indica cual cliente instalar.
Si bien a simple vista este cliente parece ser mucho mas práctico, veo que el build del proyecto esta fallando.

¿Existe algún cronograma de releases?

**Comment by eddOrnelas** [comment]
Tambien tengo la misma duda, ademas que me tira error al cobrar con tarjeta

**Comment by joelibaceta** [comment]
@leamasuero se recomienda usar esta versión, estamos trabajando en devolver la estabilidad al build.

PD: Te comparto el repositorio de la documentación.

**Comment by brunofunnie** [comment]
The whole sdk is a bug, is completely unusable, there's no standards for code response, there's no error handling, methods simple don't work and few ones who work are very poor. It's a shame that Mercado Pago such a big company have so poor implementation of a so simple thing (rest client), and the documentation.... it would be better if it doesn't exist. It confuses the developer because of the amount of information outdated and mixed.
